FEATURE: shell auto-completions
yannjor/krabby pull request #18
Opened 2024-10-04 17:35 UTC by rafaeljacov

# Added completions for the following SHELLS:
- Bash
- Zsh
- Fish
- Elvish
- Powershell

2024-10-07 09:09 UTC, yannjor requested changes

2024-10-07 09:09 UTC, yannjor commented on Cargo.toml
> +version = "0.3.0"
Pls don't update this yet, I will do it when I create a new release

2024-10-07 09:09 UTC, yannjor commented on Cargo.toml
> +clap_complete = "4.5.32"
Could be added under #Cli section

2024-10-07 09:09 UTC, yannjor commented on src/error.rs
> +    #[error("Invalid generations `{0}`, should be an integers between 1 and 9")]
Nice catch!

2024-10-07 09:09 UTC, yannjor commented on src/main.rs
> +    Init(ShellName),
Add docstring

2024-10-07 09:09 UTC, yannjor commented on src/main.rs
> +    /// Who's that pokemon!?
This is fun, but I prefer the more descriptive old version

2024-10-07 09:09 UTC, yannjor commented on src/main.rs
> +    Init(ShellName),
I don't really like 'Init' for this. A more descriptive command name would be better imo, eg 'Completions'

2024-10-07 09:09 UTC, yannjor commented on src/cli.rs
> +            arg!(--"no-mega" "Do not show mega pokemon"),
Defining the arguments again here introduces some duplication. Can we move this logic to main.rs?

2024-10-07 09:09 UTC, yannjor commented on src/cli.rs
The zsh argument completions don't work for me.

I think bash, zsh and fish completions should be enough for now.

Should we generate the completions into files., eg `krabby.bash`, `krabby.zsh` etc. That way we can also add them to the arch install script for example.

2024-12-27 13:25 UTC, rafaeljacov commented on src/cli.rs
can't really remove elvish and powershell support since the Shell struct is provided by clap_compete.
do we really need to generate them into files? I just append "krabby completions fish | source" to my config.fish and works flawlessy. It can also be done in the other shells like in .bashrc or .zshrc

2026-02-01 01:36 UTC, closed without merging